version: "v0.68.3"
repository: "github.com/VictoriaMetrics/operator"

openapi_gen_packages:
  - "github.com/VictoriaMetrics/operator/api/operator/v1"
  - "github.com/VictoriaMetrics/operator/api/operator/v1alpha1"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
  - "k8s.io/api/core/v1"
  - "k8s.io/api/apps/v1"
  - "k8s.io/api/autoscaling/v2"
  - "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1"
  - "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
  - "sigs.k8s.io/gateway-api/apis/v1"
  - "k8s.io/api/networking/v1"
  - "k8s.io/apimachinery/pkg/api/resource"
  - "k8s.io/apimachinery/pkg/apis/meta/v1"
  - "k8s.io/apimachinery/pkg/runtime"
  - "k8s.io/apimachinery/pkg/util/intstr"
  - "k8s.io/apimachinery/pkg/version"

go_dependencies:
  k8s.io/apimachinery: "v0.35.2"
  k8s.io/apiserver: "v0.35.2"
  k8s.io/kube-openapi: "v0.0.0-20260304202019-5b3e3fdb0acf"

kubernetes_swagger_url: "https://raw.githubusercontent.com/kubernetes/kubernetes/v1.35.0/api/openapi-spec/swagger.json"
title: "victoriametrics-operator CRD OpenAPI"

crd_names:
  - "github.com/VictoriaMetrics/operator/api/operator/v1.VLAgent"
  - "github.com/VictoriaMetrics/operator/api/operator/v1.VLCluster"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VLogs"
  - "github.com/VictoriaMetrics/operator/api/operator/v1.VLSingle"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMAgent"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMAlertmanagerConfig"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMAlertmanager"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMAlert"
  - "github.com/VictoriaMetrics/operator/api/operator/v1.VMAnomaly"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMAuth"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMCluster"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMNodeScrape"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMPodScrape"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMProbe"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMRule"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMScrapeConfig"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMServiceScrape"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMSingle"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMStaticScrape"
  - "github.com/VictoriaMetrics/operator/api/operator/v1beta1.VMUser"
  - "github.com/VictoriaMetrics/operator/api/operator/v1.VTCluster"
  - "github.com/VictoriaMetrics/operator/api/operator/v1.VTSingle"
  - "github.com/VictoriaMetrics/operator/api/operator/v1alpha1.VMDistributed"

crd_path: "config/crd/overlay"

host_conversion_rules:
  "github.com/VictoriaMetrics/operator": "operator.victoriametrics.com"
