resources:
- kind: Alertmanager
  group: monitoring.coreos.com
  version: v1
  plural: alertmanagers
  scope: Namespaced
  shortNames:
  - am
  definitionKey: com.coreos.monitoring.v1.Alertmanager
- kind: PodMonitor
  group: monitoring.coreos.com
  version: v1
  plural: podmonitors
  scope: Namespaced
  shortNames:
  - pmon
  definitionKey: com.coreos.monitoring.v1.PodMonitor
- kind: Probe
  group: monitoring.coreos.com
  version: v1
  plural: probes
  scope: Namespaced
  shortNames:
  - prb
  definitionKey: com.coreos.monitoring.v1.Probe
- kind: Prometheus
  group: monitoring.coreos.com
  version: v1
  plural: prometheuses
  scope: Namespaced
  shortNames:
  - prom
  definitionKey: com.coreos.monitoring.v1.Prometheus
- kind: PrometheusRule
  group: monitoring.coreos.com
  version: v1
  plural: prometheusrules
  scope: Namespaced
  shortNames:
  - promrule
  definitionKey: com.coreos.monitoring.v1.PrometheusRule
- kind: ServiceMonitor
  group: monitoring.coreos.com
  version: v1
  plural: servicemonitors
  scope: Namespaced
  shortNames:
  - smon
  definitionKey: com.coreos.monitoring.v1.ServiceMonitor
- kind: ThanosRuler
  group: monitoring.coreos.com
  version: v1
  plural: thanosrulers
  scope: Namespaced
  shortNames:
  - ruler
  definitionKey: com.coreos.monitoring.v1.ThanosRuler
- kind: AlertmanagerConfig
  group: monitoring.coreos.com
  version: v1alpha1
  plural: alertmanagerconfigs
  scope: Namespaced
  shortNames:
  - amcfg
  definitionKey: com.coreos.monitoring.v1alpha1.AlertmanagerConfig
