version: "v0.18.2"
repository: "github.com/external-secrets/external-secrets"

openapi_gen_packages:
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1alpha1"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1beta1"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1"
  - "github.com/external-secrets/external-secrets/apis/meta/v1"
  - "k8s.io/apimachinery/pkg/apis/meta/v1"
  - "k8s.io/apimachinery/pkg/runtime"
  - "k8s.io/apimachinery/pkg/version"

go_dependencies:
  k8s.io/apimachinery: "v0.33.2"
  k8s.io/apiserver: "v0.33.2"
  k8s.io/kube-openapi: "v0.0.0-20251125145642-4e65d59e963e"

kubernetes_swagger_url: "https://raw.githubusercontent.com/kubernetes/kubernetes/v1.34.1/api/openapi-spec/swagger.json"
title: "external-secrets CRD OpenAPI"

crd_names:
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1.ExternalSecret"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1.ClusterExternalSecret"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1.SecretStore"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1.ClusterSecretStore"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1alpha1.PushSecret"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1alpha1.ClusterPushSecret"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1beta1.ExternalSecret"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1beta1.ClusterExternalSecret"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1beta1.SecretStore"
  - "github.com/external-secrets/external-secrets/apis/externalsecrets/v1beta1.ClusterSecretStore"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.ECRAuthorizationToken"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.STSSessionToken"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.GCRAccessToken"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.ACRAccessToken"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.Password"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.Webhook"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.Fake"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.VaultDynamicSecret"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.GithubAccessToken"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.QuayAccessToken"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.UUID"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.Grafana"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.MFA"
  - "github.com/external-secrets/external-secrets/apis/generators/v1alpha1.ClusterGenerator"

host_conversion_rules:
  "github.com/external-secrets/external-secrets": "external-secrets.io"
