version: "v3.22.0"
repository: "github.com/open-policy-agent/gatekeeper"

openapi_gen_packages:
  - "github.com/open-policy-agent/gatekeeper/v3/apis/config/v1alpha1"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/connection/v1alpha1"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/expansion/unversioned"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/expansion/v1alpha1"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/expansion/v1beta1"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/unversioned"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1alpha1"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1beta1"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/status/v1alpha1"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/status/v1beta1"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/syncset/v1alpha1"
  - "github.com/open-policy-agent/gatekeeper/v3/pkg/mutation/match"
  - "github.com/open-policy-agent/gatekeeper/v3/pkg/mutation/types"
  - "github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1alpha1"
  - "github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1beta1"
  - "github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1"
  - "github.com/open-policy-agent/frameworks/constraint/pkg/apis/externaldata/v1alpha1"
  - "github.com/open-policy-agent/frameworks/constraint/pkg/core/templates"
  - "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
  - "k8s.io/apimachinery/pkg/apis/meta/v1"
  - "k8s.io/apimachinery/pkg/runtime"
  - "k8s.io/apimachinery/pkg/version"

go_dependencies:
  k8s.io/apimachinery: "v0.35.2"
  k8s.io/apiserver: "v0.35.2"
  k8s.io/kube-openapi: "v0.0.0-20260304202019-5b3e3fdb0acf"

kubernetes_swagger_url: "https://raw.githubusercontent.com/kubernetes/kubernetes/v1.35.0/api/openapi-spec/swagger.json"
title: "gatekeeper CRD OpenAPI"

crd_names:
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1alpha1.Assign"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1alpha1.AssignImage"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1alpha1.AssignMetadata"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1alpha1.ModifySet"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1beta1.Assign"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1beta1.AssignMetadata"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1beta1.ModifySet"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1.Assign"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1.AssignMetadata"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/mutations/v1.ModifySet"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/config/v1alpha1.Config"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/connection/v1alpha1.Connection"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/status/v1beta1.ConstraintPodStatus"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/status/v1beta1.ConstraintTemplatePodStatus"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/status/v1beta1.ExpansionTemplatePodStatus"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/status/v1beta1.MutatorPodStatus"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/status/v1beta1.ProviderPodStatus"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/syncset/v1alpha1.SyncSet"
  - "github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1.ConstraintTemplate"
  - "github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1beta1.ConstraintTemplate"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/expansion/v1alpha1.ExpansionTemplate"
  - "github.com/open-policy-agent/gatekeeper/v3/apis/expansion/v1beta1.ExpansionTemplate"
  - "github.com/open-policy-agent/frameworks/constraint/pkg/apis/externaldata/v1alpha1.Provider"

host_conversion_rules:
  "github.com/open-policy-agent/gatekeeper/v3": "gatekeeper.sh"
  "github.com/open-policy-agent/frameworks": "frameworks.gatekeeper.sh"
