resources:
- kind: Binding
  group: ''
  version: v1
  plural: bindings
  scope: Namespaced
- kind: ComponentStatus
  group: ''
  version: v1
  plural: componentstatuses
  scope: Cluster
  shortNames:
  - cs
- kind: ConfigMap
  group: ''
  version: v1
  plural: configmaps
  scope: Namespaced
  shortNames:
  - cm
- kind: Endpoints
  group: ''
  version: v1
  plural: endpoints
  scope: Namespaced
  shortNames:
  - ep
- kind: Event
  group: ''
  version: v1
  plural: events
  scope: Namespaced
  shortNames:
  - ev
- kind: LimitRange
  group: ''
  version: v1
  plural: limitranges
  scope: Namespaced
  shortNames:
  - limits
- kind: Namespace
  group: ''
  version: v1
  plural: namespaces
  scope: Cluster
  shortNames:
  - ns
- kind: Node
  group: ''
  version: v1
  plural: nodes
  scope: Cluster
  shortNames:
  - 'no'
- kind: PersistentVolume
  group: ''
  version: v1
  plural: persistentvolumes
  scope: Cluster
  shortNames:
  - pv
- kind: PersistentVolumeClaim
  group: ''
  version: v1
  plural: persistentvolumeclaims
  scope: Namespaced
  shortNames:
  - pvc
- kind: Pod
  group: ''
  version: v1
  plural: pods
  scope: Namespaced
  shortNames:
  - po
- kind: PodTemplate
  group: ''
  version: v1
  plural: podtemplates
  scope: Namespaced
- kind: ReplicationController
  group: ''
  version: v1
  plural: replicationcontrollers
  scope: Namespaced
  shortNames:
  - rc
- kind: ResourceQuota
  group: ''
  version: v1
  plural: resourcequotas
  scope: Namespaced
  shortNames:
  - quota
- kind: Secret
  group: ''
  version: v1
  plural: secrets
  scope: Namespaced
- kind: Service
  group: ''
  version: v1
  plural: services
  scope: Namespaced
  shortNames:
  - svc
- kind: ServiceAccount
  group: ''
  version: v1
  plural: serviceaccounts
  scope: Namespaced
  shortNames:
  - sa
- kind: MutatingWebhookConfiguration
  group: admissionregistration.k8s.io
  version: v1
  plural: mutatingwebhookconfigurations
  scope: Cluster
- kind: ValidatingWebhookConfiguration
  group: admissionregistration.k8s.io
  version: v1
  plural: validatingwebhookconfigurations
  scope: Cluster
- kind: ValidatingAdmissionPolicy
  group: admissionregistration.k8s.io
  version: v1alpha1
  plural: validatingadmissionpolicies
  scope: Cluster
- kind: ValidatingAdmissionPolicyBinding
  group: admissionregistration.k8s.io
  version: v1alpha1
  plural: validatingadmissionpolicybindings
  scope: Cluster
- kind: ValidatingAdmissionPolicy
  group: admissionregistration.k8s.io
  version: v1beta1
  plural: validatingadmissionpolicies
  scope: Cluster
- kind: ValidatingAdmissionPolicyBinding
  group: admissionregistration.k8s.io
  version: v1beta1
  plural: validatingadmissionpolicybindings
  scope: Cluster
- kind: CustomResourceDefinition
  group: apiextensions.k8s.io
  version: v1
  plural: customresourcedefinitions
  scope: Cluster
  shortNames:
  - crd
  - crds
- kind: APIService
  group: apiregistration.k8s.io
  version: v1
  plural: apiservices
  scope: Cluster
- kind: ControllerRevision
  group: apps
  version: v1
  plural: controllerrevisions
  scope: Namespaced
- kind: DaemonSet
  group: apps
  version: v1
  plural: daemonsets
  scope: Namespaced
  shortNames:
  - ds
- kind: Deployment
  group: apps
  version: v1
  plural: deployments
  scope: Namespaced
  shortNames:
  - deploy
- kind: ReplicaSet
  group: apps
  version: v1
  plural: replicasets
  scope: Namespaced
  shortNames:
  - rs
- kind: StatefulSet
  group: apps
  version: v1
  plural: statefulsets
  scope: Namespaced
  shortNames:
  - sts
- kind: SelfSubjectReview
  group: authentication.k8s.io
  version: v1
  plural: selfsubjectreviews
  scope: Cluster
- kind: TokenReview
  group: authentication.k8s.io
  version: v1
  plural: tokenreviews
  scope: Cluster
- kind: SelfSubjectReview
  group: authentication.k8s.io
  version: v1alpha1
  plural: selfsubjectreviews
  scope: Cluster
- kind: SelfSubjectReview
  group: authentication.k8s.io
  version: v1beta1
  plural: selfsubjectreviews
  scope: Cluster
- kind: LocalSubjectAccessReview
  group: authorization.k8s.io
  version: v1
  plural: localsubjectaccessreviews
  scope: Namespaced
- kind: SelfSubjectAccessReview
  group: authorization.k8s.io
  version: v1
  plural: selfsubjectaccessreviews
  scope: Cluster
- kind: SelfSubjectRulesReview
  group: authorization.k8s.io
  version: v1
  plural: selfsubjectrulesreviews
  scope: Cluster
- kind: SubjectAccessReview
  group: authorization.k8s.io
  version: v1
  plural: subjectaccessreviews
  scope: Cluster
- kind: HorizontalPodAutoscaler
  group: autoscaling
  version: v1
  plural: horizontalpodautoscalers
  scope: Namespaced
  shortNames:
  - hpa
- kind: HorizontalPodAutoscaler
  group: autoscaling
  version: v2
  plural: horizontalpodautoscalers
  scope: Namespaced
  shortNames:
  - hpa
- kind: CronJob
  group: batch
  version: v1
  plural: cronjobs
  scope: Namespaced
  shortNames:
  - cj
- kind: Job
  group: batch
  version: v1
  plural: jobs
  scope: Namespaced
- kind: CertificateSigningRequest
  group: certificates.k8s.io
  version: v1
  plural: certificatesigningrequests
  scope: Cluster
  shortNames:
  - csr
- kind: ClusterTrustBundle
  group: certificates.k8s.io
  version: v1alpha1
  plural: clustertrustbundles
  scope: Cluster
- kind: Lease
  group: coordination.k8s.io
  version: v1
  plural: leases
  scope: Namespaced
- kind: EndpointSlice
  group: discovery.k8s.io
  version: v1
  plural: endpointslices
  scope: Namespaced
- kind: Event
  group: events.k8s.io
  version: v1
  plural: events
  scope: Namespaced
  shortNames:
  - ev
- kind: FlowSchema
  group: flowcontrol.apiserver.k8s.io
  version: v1beta2
  plural: flowschemas
  scope: Cluster
- kind: PriorityLevelConfiguration
  group: flowcontrol.apiserver.k8s.io
  version: v1beta2
  plural: prioritylevelconfigurations
  scope: Cluster
- kind: FlowSchema
  group: flowcontrol.apiserver.k8s.io
  version: v1beta3
  plural: flowschemas
  scope: Cluster
- kind: PriorityLevelConfiguration
  group: flowcontrol.apiserver.k8s.io
  version: v1beta3
  plural: prioritylevelconfigurations
  scope: Cluster
- kind: StorageVersion
  group: internal.apiserver.k8s.io
  version: v1alpha1
  plural: storageversions
  scope: Cluster
- kind: Ingress
  group: networking.k8s.io
  version: v1
  plural: ingresses
  scope: Namespaced
  shortNames:
  - ing
- kind: IngressClass
  group: networking.k8s.io
  version: v1
  plural: ingressclasses
  scope: Cluster
- kind: NetworkPolicy
  group: networking.k8s.io
  version: v1
  plural: networkpolicies
  scope: Namespaced
  shortNames:
  - netpol
- kind: ClusterCIDR
  group: networking.k8s.io
  version: v1alpha1
  plural: clustercidrs
  scope: Cluster
  shortNames:
  - cc
- kind: IPAddress
  group: networking.k8s.io
  version: v1alpha1
  plural: ipaddresses
  scope: Cluster
  shortNames:
  - ip
- kind: RuntimeClass
  group: node.k8s.io
  version: v1
  plural: runtimeclasses
  scope: Cluster
- kind: PodDisruptionBudget
  group: policy
  version: v1
  plural: poddisruptionbudgets
  scope: Namespaced
  shortNames:
  - pdb
- kind: ClusterRole
  group: rbac.authorization.k8s.io
  version: v1
  plural: clusterroles
  scope: Cluster
- kind: ClusterRoleBinding
  group: rbac.authorization.k8s.io
  version: v1
  plural: clusterrolebindings
  scope: Cluster
- kind: Role
  group: rbac.authorization.k8s.io
  version: v1
  plural: roles
  scope: Namespaced
- kind: RoleBinding
  group: rbac.authorization.k8s.io
  version: v1
  plural: rolebindings
  scope: Namespaced
- kind: PodSchedulingContext
  group: resource.k8s.io
  version: v1alpha2
  plural: podschedulingcontexts
  scope: Namespaced
- kind: ResourceClaim
  group: resource.k8s.io
  version: v1alpha2
  plural: resourceclaims
  scope: Namespaced
- kind: ResourceClaimTemplate
  group: resource.k8s.io
  version: v1alpha2
  plural: resourceclaimtemplates
  scope: Namespaced
- kind: ResourceClass
  group: resource.k8s.io
  version: v1alpha2
  plural: resourceclasses
  scope: Cluster
- kind: PriorityClass
  group: scheduling.k8s.io
  version: v1
  plural: priorityclasses
  scope: Cluster
  shortNames:
  - pc
- kind: CSIDriver
  group: storage.k8s.io
  version: v1
  plural: csidrivers
  scope: Cluster
- kind: CSINode
  group: storage.k8s.io
  version: v1
  plural: csinodes
  scope: Cluster
- kind: CSIStorageCapacity
  group: storage.k8s.io
  version: v1
  plural: csistoragecapacities
  scope: Namespaced
- kind: StorageClass
  group: storage.k8s.io
  version: v1
  plural: storageclasses
  scope: Cluster
  shortNames:
  - sc
- kind: VolumeAttachment
  group: storage.k8s.io
  version: v1
  plural: volumeattachments
  scope: Cluster
